version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: django-quizlet-prod
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=quizproject.settings
    restart: unless-stopped
